### ISSUE TITLE
Workflow failed on inquiry functions in Ubuntu machine

### ISSUE THREAD

**Issue by Jonathanlyj** [NU-CUCIS/pnetcdf-python#2]
The github action (.github/workflows/build_test_latest_c.yml) created for building and testing on Ubuntu machines currently fails on some file inquire steps with the following error message on test program. Full error message can be found in github action log.

`**** stack smashing detected ***`

Identified inquire function that triggers this include File.inq_buff_size and File.inq_buff_usage which internally calls ncmpi_inq_buffer_size/ ncmpi_inq_buffer_usage c functions

**Comment by yzanhua** [comment]
Might due to a type mismatch between `MPI_Offset` and `int`: [here](https://github.com/NU-CUCIS/pnetcdf-python/blob/e82427781454204f3ce0ddc007941de15722b4af/src/pncpy/_File.pyx#L781C53-L781C63)

1. try `long long` instead
2. modify each occurrence accordingly
